using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace HotelManagementSystem
{
    public partial class FormLogin : Form
    {
        public FormLogin()
        {
            // Feature: Initializes the visual components of the form generated by the designer
            InitializeComponent();
        }

        private void btnLogin_Click(object sender, EventArgs e)
        {
            string username = txtUsername.Text.Trim();
            string password = txtPassword.Text;

            // Feature: Pre-flight validation to ensure both fields contain data before executing database operations
            if (string.IsNullOrEmpty(username) || string.IsNullOrEmpty(password))
            {
                MessageBox.Show("Please enter both Username and Password.", "Login Validation",
                    MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            // Feature: Parameterized database query structure to explicitly protect the application against SQL injection attacks
            string query = "SELECT * FROM `users` WHERE username = @User AND password = @Pass";

            MySqlParameter[] parameters = new MySqlParameter[]
            {
                new MySqlParameter("@User", MySqlDbType.VarChar) { Value = username },
                new MySqlParameter("@Pass", MySqlDbType.VarChar) { Value = password }
            };

            DataTable dt = DatabaseConnection.ExecuteQuery(query, parameters);

            // Feature: Evaluates the datatable response to confirm a successful authentication match in the database
            if (dt != null && dt.Rows.Count > 0)
            {
                string fullName = dt.Rows[0]["full_name"].ToString();
                string role = dt.Rows[0]["role"].ToString();

                MessageBox.Show($"Welcome, {fullName}! Logged in successfully as {role}.", "Login Successful",
                    MessageBoxButtons.OK, MessageBoxIcon.Information);

                // Feature: Persists the authenticated user's credentials globally to maintain state across form navigations
                UserSession.Username = fullName;
                UserSession.Role = role;

                // Feature: Transitions the user to the main dashboard. Hides the login screen and binds the application's closure to the main form to prevent ghost processes.
                FormMain mainForm = new FormMain(fullName, role);
                this.Hide();
                mainForm.FormClosed += (s, args) => this.Close();
                mainForm.Show();
            }
            else
            {
                // Feature: Automatically clears the password field and refocuses input on authentication failure to streamline user retries
                MessageBox.Show("Invalid Username or Password. Please try again.", "Login Failed",
                    MessageBoxButtons.OK, MessageBoxIcon.Error);
                txtPassword.Clear();
                txtUsername.Focus();
            }

        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
            // Feature: Immediately terminates the application and closes all associated threads
            Application.Exit();
        }
    }
}